name: Build and deploy to S3

on:
  push:
    branches: [ "master" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Run generate documentation
      env:
        TESTING: ${{ secrets.TESTING }}
      run: |
        echo $TESTING
        echo $TESTING > /tmp/testing.txt
      
    - name: Archive wiki artifact
      uses: actions/upload-artifact@v3
      with:
        name: save build artifact
        path: |
          /tmp/testing.txt